apiVersion: apps/v1
kind: Deployment
metadata:
  name: testbench
  labels:
    app: testbench
spec:
  selector:
    matchLabels:
      app: testbench
  replicas: 1
  template:
    metadata:
      labels:
        app: testbench
    spec:
      containers:
        - name: testbench
          image: gcr.io/zeebe-io/zeebe-cluster-testbench:1.x-dev
          imagePullPolicy: Always
          env:
            - name: ZCTB_AUTHENTICATION_SERVER_URL
              value: "https://login.cloud.ultrawombat.com/oauth/token"
            - name: ZCTB_CLIENT_ID
              value: "9nXUMVqejyftot44BeGDYzAm16paBHhD"
            - name: ZCTB_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: testbench-secrets
                  key: clientSecret
            - name: ZCTB_CONTACT_POINT
              valueFrom:
                secretKeyRef:
                  name: testbench-secrets
                  key: contactPoint
            - name: ZCTB_CLOUD_API_URL
              value: "https://api.cloud.ultrawombat.com/"
            - name: ZCTB_CLOUD_AUDIENCE
              value: "api.cloud.ultrawombat.com"
            - name: ZCTB_CLOUD_AUTHENTICATION_SERVER_URL
              value: "https://login.cloud.ultrawombat.com/oauth/token"
            - name: ZCTB_CLOUD_CLIENT_ID
              value: "oMgf5fM6MKLLhrAU"
            - name: ZCTB_CLOUD_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: testbench-secrets
                  key: cloudClientSecret
            - name: ZCTB_INTERNAL_CLOUD_AUTHENTICATION_SERVER_URL
              value: "https://weblogin.cloud.ultrawombat.com/oauth/token"
            - name: ZCTB_INTERNAL_CLOUD_API_URL
              value: "https://console.cloud.ultrawombat.com/"
            - name: ZCTB_INTERNAL_CLOUD_AUDIENCE
              value: "cloud.ultrawombat.com"
            - name: ZCTB_INTERNAL_CLOUD_CLIENT_ID
              value: "0Z2Ohfu3lVzDjtv8rYcGRZtUxrKa2Q96"
            - name: ZCTB_INTERNAL_CLOUD_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: testbench-secrets
                  key: internalCloudClientSecret
            - name: ZCTB_INTERNAL_CLOUD_USERNAME
              value: "zeebe@camunda.com"
            - name: ZCTB_INTERNAL_CLOUD_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: testbench-secrets
                  key: internalCloudPassword
            - name: ZCTB_SLACK_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: testbench-secrets
                  key: slackWebhookUrl
          resources:
            limits:
              cpu: 4
              memory: 256Mi
            requests:
              cpu: 2
              memory: 100Mi
