apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: zeebe-chaos-rolebinding
  labels:
    app.kubernetes.io/component: remote
    app.kubernetes.io/name: zeebe-chaos
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: zeebe-chaos-role
subjects:
- kind: ServiceAccount
  name: zeebe-chaos-sa
  namespace: zeebe-chaos
